language: generic
deploy:
  provider: releases
  token: $GITHUB_OAUTH_TOKEN
  file: "./app/build/outputs/apk/production/release/app-production-release-unsigned.apk"
  skip_cleanup: true
  draft: true
os: osx
osx_image: xcode8.3
env:
  global:
    - ANDROID_HOME=/Users/travis/opt
    - SDK_FILENAME=sdk-tools-darwin-4333796.zip
    - HOMEBREW_NO_AUTO_UPDATE=1
install:
  - mkdir -p $HOME/opt && curl -sSO https://dl.google.com/android/repository/${SDK_FILENAME} && unzip -qq ${SDK_FILENAME} -d $HOME/opt &> /dev/null
  - brew install uncrustify gnu-sed &> /dev/null
  - yes | $HOME/opt/tools/bin/sdkmanager "tools" "platform-tools" &> /dev/null
  - yes | $HOME/opt/tools/bin/sdkmanager "build-tools;29.0.2" &> /dev/null
  - yes | $HOME/opt/tools/bin/sdkmanager "platforms;android-29" &> /dev/null
script:
  - export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
  - ./tools/uncrustify && git diff && git diff --quiet
  - ./gradlew lintProductionRelease
  - ./gradlew assembleProductionRelease
notifications:
  email: false
